### ISSUE TITLE
from fretboardgtr.fretboard import FretBoard fails in python 3.11.3

### ISSUE THREAD

**Issue by cryptochaos** [antscloud/fretboardgtr#20]
Looks like an issue with using     @dataclass 

-----------------------------------------------[ exception ]------------------------------------------

/Users/paul/PycharmProjects/GuitarChord/venv/bin/python /Users/paul/PycharmProjects/GuitarChord/guitar_chord_generator.py 
Traceback (most recent call last):
  File "/Users/paul/PycharmProjects/GuitarChord/guitar_chord_generator.py", line 1, in <module>
    from fretboardgtr.fretboard import FretBoard, FretBoardConfig
  File "/Users/paul/PycharmProjects/GuitarChord/venv/lib/python3.11/site-packages/fretboardgtr/__init__.py", line 16, in <module>
    from fretboardgtr.fretboard import FretBoard, VerticalFretBoard
  File "/Users/paul/PycharmProjects/GuitarChord/venv/lib/python3.11/site-packages/fretboardgtr/fretboard.py", line 7, in <module>
    from fretboardgtr.fretboards.base import FretBoardLike
  File "/Users/paul/PycharmProjects/GuitarChord/venv/lib/python3.11/site-packages/fretboardgtr/fretboards/base.py", line 6, in <module>
    from fretboardgtr.fretboards.config import FretBoardConfig
  File "/Users/paul/PycharmProjects/GuitarChord/venv/lib/python3.11/site-packages/fretboardgtr/fretboards/config.py", line 16, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fretboardgtr.note_colors.NoteColors'> for field open_colors is not allowed: use default_factory

**Comment by antscloud** [comment]
Thank you for reporting this issue :+1: 
It should be fixed in the next release
